[package]
name = "mmlx"
description = "MML parser and compiler with MXDRV MML input and MDX output support."
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["h1romas4 <h1romas4@gmail.com>"]
homepage = "https://github.com/h1romas4"
repository = "https://github.com/h1romas4/chipstream"
readme = "README.md"
keywords = ["mml", "mdx", "mxdrv", "compiler", "music"]
categories = ["multimedia::audio"]

[dependencies]
pest = "2.9.1"
pest_derive = "2.9.1"
soundlog = { workspace = true, features = ["mdx"] }
