//! Position-aware MXDRV MML APIs. Enabled by the `source-map` feature.
//!
//! [`parse`] collects syntax ranges separately from the ordinary MDX AST;
//! [`compile`] returns a soundlog document with a map of finalized output
//! coordinates. Neither operation reparses the source to locate diagnostics.
//! Ordinary [`super::parse`] and [`super::compile()`] remain map-free with this
//! feature enabled. Source lookup uses retained maps rather than recompilation.
//!
//! # Source Maps
//!
//! [`SyntaxMap`] covers metadata, voices, numeric arguments, commands, and nested
//! repeats. [`MdxLocation`] addresses finalized track commands, tones, title, or
//! PDX filename. Split notes share their originating command range. Synthetic
//! output, including inserted PCM mode and track terminators, has no source range.
//! Output maps identify the primary origin, not every contributing state change.
//! See [`crate::frontend`] for shared ownership and memory characteristics.
//!
//! # Examples
//!
//! ```
//! use mmlx::mdx::frontend::{self, MdxLocation};
//!
//! let source = "A c4 d4";
//! let parsed = frontend::parse(source)?;
//! let compiled = frontend::compile(&parsed)?;
//! drop(parsed);
//!
//! let location = MdxLocation::TrackCommand { track: 0, index: 0 };
//! let span = compiled.source_map().get(&location).unwrap();
//! assert_eq!(span.text(source), Some("c4"));
//! let position = compiled.source().position(span.start()).unwrap();
//! assert_eq!((position.line_number, position.column), (1, 3));
//!
//! assert!(!compiled.document().to_bytes().unwrap().is_empty());
//! # Ok::<(), mmlx::diagnostic::Diagnostic>(())
//! ```

mod location;
mod syntax;

use soundlog::mdx::document::MdxDocument;

use super::compile::{CompileError, CompileSourceContext, compile_internal};
use super::mml::{MmlDocument, MmlSourceMap, parse_internal};
use crate::diagnostic::Diagnostic;
use crate::frontend::{Compiled, MappedAst, SourceFile, SourceMap};

pub use location::MdxLocation;
pub use syntax::{ArgumentSource, CommandSource, SyntaxMap, VoiceSource};

/// A read-only MDX AST and syntax map borrowing their original source snapshot.
pub type ParsedMml<'source> = MappedAst<'source, MmlDocument, SyntaxMap>;
/// A finalized soundlog MDX document and output map borrowing the original source.
pub type CompiledMdx<'source> = Compiled<'source, MdxDocument, MdxLocation>;

/// Parse once, borrowing the input and retaining separate syntax ranges.
///
/// Does not copy the input or construct a line index. The returned artifact
/// must not outlive `source`; its AST and syntax map are owned allocations.
///
/// # Errors
///
/// Returns a [`Diagnostic`] for invalid syntax, repeat structure, numeric values,
/// or an input larger than `u32::MAX` bytes. A diagnostic range, when available,
/// addresses the original UTF-8 source; source lines are not copied into errors.
pub fn parse(source: &str) -> Result<ParsedMml<'_>, Diagnostic> {
    let source_file = SourceFile::new(source).ok_or_else(|| {
        Diagnostic::error(
            "mmlx.source-too-large",
            "MML source exceeds the 32-bit byte range",
            None,
        )
    })?;
    let mut syntax = MmlSourceMap::default();
    let ast = parse_internal(source, Some(&mut syntax)).map_err(|error| error.into_diagnostic())?;
    Ok(MappedAst::new(source_file, ast, SyntaxMap::new(syntax)))
}

/// Compile once and retain a map addressing the finalized document.
///
/// The result borrows the source, not `parsed`, so the AST and syntax map may be
/// dropped after compilation. Generated bytes match ordinary [`super::compile()`].
/// The output map is allocated separately from the soundlog document.
///
/// # Errors
///
/// Returns a [`Diagnostic`] when a channel, voice, value, or command cannot be
/// represented in MDX, or the soundlog builder rejects the document. Builder
/// failures may have no source range; command failures use the responsible span.
pub fn compile<'source>(parsed: &ParsedMml<'source>) -> Result<CompiledMdx<'source>, Diagnostic> {
    let mut context = CompileSourceContext::new(parsed.syntax().inner());
    let document = compile_internal(parsed.ast(), Some(&mut context)).map_err(|error| {
        let code = match error {
            CompileError::InvalidChannel(_) => "mmlx.mdx.invalid-channel",
            CompileError::InvalidVoice { .. } => "mmlx.mdx.invalid-voice",
            CompileError::InvalidValue { .. } => "mmlx.mdx.invalid-value",
            CompileError::UnsupportedCommand(_) => "mmlx.mdx.unsupported-command",
            CompileError::Builder(_) => "mmlx.mdx.builder",
        };
        Diagnostic::error(code, error.to_string(), context.error_span)
    })?;
    let syntax = parsed.syntax();
    let mut groups = Vec::with_capacity(18);
    groups.extend(context.output_map);
    groups.push(
        syntax
            .voices()
            .iter()
            .map(|voice| Some(voice.span))
            .collect(),
    );
    groups.push(vec![syntax.title(), syntax.pcm_file()]);
    Ok(Compiled::new(
        parsed.source(),
        document,
        SourceMap::new(groups, MdxLocation::coordinates),
    ))
}
